unique_ids:
  assets:
    standard-page.html: I7Y47UDXZFFLB47ZLXR2YLUQVV6FYMQ2
    theme.css: JIGC7TL7KSQBFS6LJ6JAIBR6FL4BJ5RH
  forms:
    Form1: SRMU6V2LADF6B34XGUCP6BLSW4GBIHKH
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1730891794351984551208065.2981'
